FROM --platform=linux/amd64 ubuntu:latest

RUN apt-get update
RUN apt-get install -y nasm build-essential gdb
RUN apt-get install -y python3
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY . .
#COPY entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh

#ENTRYPOINT ./trace_memory.sh
