#!/usr/bin/env python3
"""Generates hornet_typedesc_tags.h from the live _TYPEDESC_* constants
in codegen/strings.py.

Python's own type-descriptor builder (_get_or_build_type_descriptor)
is the single source of truth for these tag values -- this script
reads them via ordinary Python introspection (import + getattr), not
by re-parsing strings.py's own source text, specifically so the
generated header can never drift out of sync with what the compiler
actually emits: if the values change, importing codegen.strings picks
up the change automatically, with no separate parser of its own to
fall out of date.

This closes off exactly one, narrow kind of ABI drift -- the tag
VALUES matching between the two languages. It does NOT cover the
structural layout of a multi-field descriptor (ARRAY/SLICE/STRUCT's
own field order and width), which has no single source of truth to
generate from today and is still kept in sync by hand, with mirrored
documentation on both the Python and C sides -- see this repository's
runtime/README.md (once it exists) or the docstring of
_get_or_build_type_descriptor for that layout.

Usage: python3 runtime/generate_typedesc_header.py
Run this whenever codegen/strings.py's own _TYPEDESC_* constants
change, and check in the result -- there is currently no build step
that runs this automatically (see the eventual build script's own
design).
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = Path(__file__).resolve().parent / "hornet_typedesc_tags.h"


def _collect_typedesc_constants() -> list[tuple[str, int]]:
    """Imports codegen.strings and returns every _TYPEDESC_* constant
    it defines, as (c_name, value) pairs -- c_name has the leading
    underscore stripped and an HORNET_ prefix added (_TYPEDESC_INT ->
    HORNET_TYPEDESC_INT), sorted by value so the generated header's
    own ordering is meaningful (ascending tag order) regardless of
    whatever order they happen to be declared in on the Python side.
    """
    sys.path.insert(0, str(REPO_ROOT))
    import codegen.strings as strings_module

    pattern = re.compile(r"^_TYPEDESC_[A-Z0-9]+$")
    constants = [
        (name, value)
        for name, value in vars(strings_module).items()
        if pattern.match(name) and isinstance(value, int)
    ]
    if not constants:
        raise RuntimeError(
            "No _TYPEDESC_* constants found in codegen.strings -- either "
            "they were renamed/removed, or this script's own pattern "
            "needs updating to match."
        )
    constants.sort(key=lambda pair: pair[1])
    return [(f"HORNET_{name.lstrip('_')}", value) for name, value in constants]


def _render_header(constants: list[tuple[str, int]]) -> str:
    lines = [
        "// AUTO-GENERATED -- DO NOT EDIT BY HAND.",
        "//",
        "// Generated by runtime/generate_typedesc_header.py from the",
        "// live _TYPEDESC_* constants in codegen/strings.py, which is",
        "// the single source of truth for these values. Re-run that",
        "// script and check in the result whenever those Python",
        "// constants change -- see this file's own generator for why",
        "// these specific integers, and what this generation step",
        "// does and does not cover.",
        "#ifndef HORNET_TYPEDESC_TAGS_H",
        "#define HORNET_TYPEDESC_TAGS_H",
        "",
    ]
    name_width = max(len(name) for name, _ in constants)
    for name, value in constants:
        lines.append(f"#define {name.ljust(name_width)} {value}")
    lines.append("")
    lines.append("#endif  // HORNET_TYPEDESC_TAGS_H")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    constants = _collect_typedesc_constants()
    header_text = _render_header(constants)
    OUTPUT_PATH.write_text(header_text)
    print(f"Wrote {OUTPUT_PATH} ({len(constants)} tag constants).")


if __name__ == "__main__":
    main()
