#!/usr/bin/env python3
"""Generate hornet_typedesc_tags.h from the _TYPEDESC_* constants in ir/typedesc.py."""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = Path(__file__).resolve().parent / "hornet_typedesc_tags.h"


def _collect_typedesc_constants() -> list[tuple[str, int]]:
    """(c_name, value) for each _TYPEDESC_* constant, as HORNET_TYPEDESC_*."""
    sys.path.insert(0, str(REPO_ROOT))
    import ir.typedesc as strings_module

    pattern = re.compile(r"^_TYPEDESC_[A-Z0-9]+$")
    constants = [
        (name, value)
        for name, value in vars(strings_module).items()
        if pattern.match(name) and isinstance(value, int)
    ]
    if not constants:
        raise RuntimeError(
            "No _TYPEDESC_* constants found in ir.typedesc -- either "
            "they were renamed/removed, or this script's own pattern "
            "needs updating to match."
        )
    constants.sort(key=lambda pair: pair[1])
    return [(f"HORNET_{name.lstrip('_')}", value) for name, value in constants]


def _render_header(constants: list[tuple[str, int]]) -> str:
    lines = [
        "// AUTO-GENERATED by runtime/generate_typedesc_header.py from ir/typedesc.py. Do not edit.",
        "#ifndef HORNET_TYPEDESC_TAGS_H",
        "#define HORNET_TYPEDESC_TAGS_H",
        "",
    ]
    name_width = max(len(name) for name, _ in constants)
    for name, value in constants:
        lines.append(f"#define {name.ljust(name_width)} {value}")
    lines.append("")
    lines.append("#endif  // HORNET_TYPEDESC_TAGS_H")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    constants = _collect_typedesc_constants()
    header_text = _render_header(constants)
    OUTPUT_PATH.write_text(header_text)
    print(f"Wrote {OUTPUT_PATH} ({len(constants)} tag constants).")


if __name__ == "__main__":
    main()
