// AUTO-GENERATED -- DO NOT EDIT BY HAND.
//
// Generated by runtime/generate_typedesc_header.py from the
// live _TYPEDESC_* constants in ir/strings.py, which is
// the single source of truth for these values. Re-run that
// script and check in the result whenever those Python
// constants change -- see this file's own generator for why
// these specific integers, and what this generation step
// does and does not cover.
#ifndef HORNET_TYPEDESC_TAGS_H
#define HORNET_TYPEDESC_TAGS_H

#define HORNET_TYPEDESC_INT    0
#define HORNET_TYPEDESC_BOOL   1
#define HORNET_TYPEDESC_STR    2
#define HORNET_TYPEDESC_ARRAY  3
#define HORNET_TYPEDESC_SLICE  4
#define HORNET_TYPEDESC_STRUCT 5
#define HORNET_TYPEDESC_INT8   6
#define HORNET_TYPEDESC_UINT8  7
#define HORNET_TYPEDESC_INT64  8
#define HORNET_TYPEDESC_SUM    9

#endif  // HORNET_TYPEDESC_TAGS_H
